apiVersion: v1
kind: Pod
metadata:
  name: env-secret-pod
spec:
  containers:
  - name: busybox
    image: busybox:stable
    command: ["/bin/sh" , "-c"]
    args: ["sleep 3600"]
    env:
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: username

