apiVersion: v1
kind: Pod
metadata:
  labels:
    run: annotated-pod
  name: annotated-pod
spec:
  containers:
  - image: nginx:1.25.1
    name: annotated-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
