apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-pod-creator
  namespace: ckad
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-creator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: Jide
