apiVersion: v1
kind: Pod
metadata:
 name: app-consuming-pvc
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 10; done"]
    ports:
    - containerPort: 80 
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    volumeMounts:
    - mountPath: "/mnt/data/"
      name: db-pv
  volumes:
    - name: db-pv
      persistentVolumeClaim:
        claimName: db-pvc
