
apiVersion: v1
kind: Pod
metadata:
 name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 10; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    volumeMounts:
    - name: log-volume
      mountPath: "/var/log/nginx"
  volumes:
  - name: log-volume
    persistentVolumeClaim:
      claimName: logs-pvc  
