
apiVersion: v1
kind: Pod
metadata:
 name: multi-container-app
spec:
  containers:
  - name: container1
    image: arm64v8/alpine:3.12.0
    command: ["/bin/sh",]
    args: ["-c", "while true; do sleep 10; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    volumeMounts:
    - name: pod-volume
      mountPath: "/etc/a"    
  - name: container2
    image: arm64v8/alpine:3.12.0
    command: ["/bin/sh",]
    args: ["-c", "while true; do sleep 10; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    volumeMounts:
    - mountPath: "/etc/b"
      name: pod-volume
  volumes:
  - name: pod-volume
    emptyDir: {}

