apiVersion: v1
kind: Pod
metadata:
  labels:
   app: complex-pod
  name: complex-pod
spec:
  initContainers:
  - name: setup
    image: alpine:3.12.0
    command: ['sh', '-c', "wget -O- google.com"]
  containers:
  - image: nginx:1.25.1
    name: complex-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
